-- Erstellen der Tabellen für Jira 2.0

-- 1. Benutzer (Users)
CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Projekte (Projects)
CREATE TABLE IF NOT EXISTS projects (
    project_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INT default null,
    FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 3. Aufgaben (Tasks/Issues)
CREATE TABLE IF NOT EXISTS tasks (
    task_id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    assigned_to INT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status ENUM('To Do', 'In Progress', 'Done', 'Blocked') DEFAULT 'To Do',
    priority ENUM('Low', 'Medium', 'High') DEFAULT 'Medium',
    deadline DATETIME,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(user_id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE SET NULL
);

-- 4. Kommentare (Comments)
CREATE TABLE IF NOT EXISTS comments (
    comment_id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    user_id INT NOT NULL,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES tasks(task_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 5. Projektmitglieder (Project Members)
CREATE TABLE IF NOT EXISTS project_members (
    member_id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    user_id INT NOT NULL,
    role ENUM('Developer', 'Admin', 'Viewer') DEFAULT 'Viewer',
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_project_user (project_id, user_id),
    FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Testdaten

-- Benutzer
INSERT INTO users (username, email, password) VALUES
('christian', 'christian@example.com', 'PasswortChristian123'),
('alex', 'alex@example.com', 'PasswortAlex123'),
('melina', 'melina@example.com', 'PasswortMelina123'),
('luca', 'luca@example.com', 'PasswortLuca123');

-- Projekte
INSERT INTO projects (name, description , created_by) VALUES 
('Verteilte Systeme Projekt', 'Entwicklung einer skalierbaren Jira-Alternative mit Docker und Node.js.', 1),
('Frontend Redesign', 'Modernisierung der Benutzeroberfäche auf Basis von Angular 19.', 1);

-- Projektmitglieder zuweisen
INSERT INTO project_members (project_id, user_id, role) VALUES 
(1, 1, 'Admin'),
(1, 2, 'Developer'),
(1, 3, 'Developer'),
(2, 1, 'Admin'),
(2, 3, 'Developer'),
(2, 2, 'Viewer');

-- Aufgaben für Projekt 1
INSERT INTO tasks (project_id, title, description, status, assigned_to, created_by) VALUES 
(1, 'Datenbank aufsetzen', 'Tabellenstruktur in init.sql definieren und Constraints prüfen.', 'Done', 2, 1),
(1, 'Backend API implementieren', 'REST Endpoints für Projekte und Tasks erstellen.', 'In Progress', 2, 1),
(1, 'Dockerisierung', 'Dockerfile und docker-compose.yaml für das gesamte System erstellen.', 'To Do', 3, 1),
(1, 'Load Balancer konfigurieren', 'Nginx für horizontales Skalieren der Backend-Instanzen einrichten.', 'To Do', 1, 1);

-- Aufgaben für Projekt 2
INSERT INTO tasks (project_id, title, description, status, assigned_to, created_by) VALUES 
(2, 'Landing Page erstellen', 'Neues Dashboard-Design mit Angular Komponenten umsetzen.', 'In Progress', 3, 1),
(2, 'Login Komponente bauen', 'Authentifizierungsmaske mit JWT Integration.', 'Done', 3, 1),
(2, 'Responsive Design', 'Optimierung der Views für mobile Endgeräte.', 'To Do', 2, 1);

-- Neue Testdaten (Generiert)

-- Zusätzliche Benutzer
INSERT INTO users (username, email, password) VALUES
('marcel.bauer79', 'marcel.bauer79@example.com', 'PasswortMarcel808'),
('julian.schröder92', 'julian.schröder92@example.com', 'PasswortJulian815'),
('daniela.schmid41', 'daniela.schmid41@example.com', 'PasswortDaniela431'),
('daniel.krause40', 'daniel.krause40@example.com', 'PasswortDaniel950'),
('jan.neumann29', 'jan.neumann29@example.com', 'PasswortJan658'),
('emma.koch76', 'emma.koch76@example.com', 'PasswortEmma544'),
('melanie.koch54', 'melanie.koch54@example.com', 'PasswortMelanie377'),
('emma.schneider78', 'emma.schneider78@example.com', 'PasswortEmma120'),
('julia.schmitz60', 'julia.schmitz60@example.com', 'PasswortJulia883'),
('jessica.zimmermann72', 'jessica.zimmermann72@example.com', 'PasswortJessica273'),
('ben.werner54', 'ben.werner54@example.com', 'PasswortBen307'),
('finn.klein57', 'finn.klein57@example.com', 'PasswortFinn680'),
('marie.wagner26', 'marie.wagner26@example.com', 'PasswortMarie959'),
('max.braun74', 'max.braun74@example.com', 'PasswortMax106'),
('ben.schmitt50', 'ben.schmitt50@example.com', 'PasswortBen415'),
('daniel.hartmann17', 'daniel.hartmann17@example.com', 'PasswortDaniel522'),
('stefanie.weber31', 'stefanie.weber31@example.com', 'PasswortStefanie136'),
('tobi.meier82', 'tobi.meier82@example.com', 'PasswortTobi972'),
('stefan.braun57', 'stefan.braun57@example.com', 'PasswortStefan150'),
('martin.schulz97', 'martin.schulz97@example.com', 'PasswortMartin256'),
('lukas.fischer43', 'lukas.fischer43@example.com', 'PasswortLukas229'),
('thomas.becker98', 'thomas.becker98@example.com', 'PasswortThomas473'),
('kevin.richter39', 'kevin.richter39@example.com', 'PasswortKevin599'),
('daniela.weiß95', 'daniela.weiß95@example.com', 'PasswortDaniela923'),
('nadine.schmitz25', 'nadine.schmitz25@example.com', 'PasswortNadine596'),
('nico.huber79', 'nico.huber79@example.com', 'PasswortNico730'),
('clara.scholz18', 'clara.scholz18@example.com', 'PasswortClara803'),
('andreas.walter60', 'andreas.walter60@example.com', 'PasswortAndreas917'),
('marie.fischer19', 'marie.fischer19@example.com', 'PasswortMarie316'),
('elias.krause15', 'elias.krause15@example.com', 'PasswortElias780'),
('leni.fischer16', 'leni.fischer16@example.com', 'PasswortLeni544'),
('tobi.meyer29', 'tobi.meyer29@example.com', 'PasswortTobi636'),
('ben.werner34', 'ben.werner34@example.com', 'PasswortBen911'),
('philipp.möller30', 'philipp.möller30@example.com', 'PasswortPhilipp286'),
('paul.weiß23', 'paul.weiß23@example.com', 'PasswortPaul289'),
('noah.müller62', 'noah.müller62@example.com', 'PasswortNoah445'),
('lena.schmitt78', 'lena.schmitt78@example.com', 'PasswortLena597'),
('finn.becker35', 'finn.becker35@example.com', 'PasswortFinn564'),
('laura.meyer39', 'laura.meyer39@example.com', 'PasswortLaura710'),
('david.fuchs77', 'david.fuchs77@example.com', 'PasswortDavid172'),
('philipp.maier93', 'philipp.maier93@example.com', 'PasswortPhilipp664'),
('emma.köhler10', 'emma.köhler10@example.com', 'PasswortEmma929'),
('nadine.walter66', 'nadine.walter66@example.com', 'PasswortNadine393'),
('lukas.lange38', 'lukas.lange38@example.com', 'PasswortLukas553'),
('fabian.herrmann41', 'fabian.herrmann41@example.com', 'PasswortFabian939'),
('erik.schmitz82', 'erik.schmitz82@example.com', 'PasswortErik205'),
('julia.jung30', 'julia.jung30@example.com', 'PasswortJulia907'),
('sophia.peters74', 'sophia.peters74@example.com', 'PasswortSophia123'),
('dennis.müller40', 'dennis.müller40@example.com', 'PasswortDennis411'),
('nicole.schubert42', 'nicole.schubert42@example.com', 'PasswortNicole132'),
('lena.kaiser90', 'lena.kaiser90@example.com', 'PasswortLena460'),
('erik.mayer44', 'erik.mayer44@example.com', 'PasswortErik937'),
('sophie.krause75', 'sophie.krause75@example.com', 'PasswortSophie136'),
('noah.kaiser33', 'noah.kaiser33@example.com', 'PasswortNoah425'),
('anna.müller93', 'anna.müller93@example.com', 'PasswortAnna273'),
('max.fischer59', 'max.fischer59@example.com', 'PasswortMax677'),
('mila.maier44', 'mila.maier44@example.com', 'PasswortMila473'),
('vanessa.jung21', 'vanessa.jung21@example.com', 'PasswortVanessa872'),
('noah.lange50', 'noah.lange50@example.com', 'PasswortNoah155'),
('paul.schulze49', 'paul.schulze49@example.com', 'PasswortPaul724'),
('hannah.krause65', 'hannah.krause65@example.com', 'PasswortHannah966'),
('nadine.hahn52', 'nadine.hahn52@example.com', 'PasswortNadine538'),
('martin.schröder90', 'martin.schröder90@example.com', 'PasswortMartin596'),
('vanessa.müller82', 'vanessa.müller82@example.com', 'PasswortVanessa742'),
('markus.hofmann78', 'markus.hofmann78@example.com', 'PasswortMarkus895'),
('felix.lange93', 'felix.lange93@example.com', 'PasswortFelix783'),
('stefan.fuchs59', 'stefan.fuchs59@example.com', 'PasswortStefan390'),
('thomas.richter48', 'thomas.richter48@example.com', 'PasswortThomas220'),
('nadine.fischer32', 'nadine.fischer32@example.com', 'PasswortNadine167'),
('noah.jung33', 'noah.jung33@example.com', 'PasswortNoah813');

-- Zusätzliche Projekte
INSERT INTO projects (name, description, created_by) VALUES
('Investition und Finanzierung', 'Analyse von Investitionsprojekten und Finanzierungsmodellen.', 1),
('E-Business', 'Entwicklung von Strategien für den elektronischen Handel.', 3),
('Mobile App Dev', 'Programmierung von nativen und hybriden mobilen Anwendungen.', 3),
('Datenbanken II', 'Fortgeschrittene Konzepte der Datenbankmodellierung und SQL-Optimierung.', 3),
('IT-Projektmanagement', 'Planung und Steuerung von IT-Projekten nach agilen Methoden.', 2),
('Business Intelligence', 'Datenanalyse und Visualisierung zur Entscheidungsunterstützung.', 1),
('Cloud Computing', 'Architektur und Implementierung von Cloud-Infrastrukturen.', 2),
('Software Qualitätssicherung', 'Teststrategien und Qualitätssicherungsmaßnahmen in der Softwareentwicklung.', 1),
('Enterprise Resource Planning', 'Einführung und Anpassung von ERP-Systemen wie SAP.', 2),
('IT-Sicherheit', 'Maßnahmen zum Schutz von IT-Systemen und Netzwerken.', 3);

-- Zusätzliche Projektmitglieder
INSERT INTO project_members (project_id, user_id, role) VALUES
(3, 1, 'Admin'),
(3, 2, 'Viewer'),
(3, 27, 'Viewer'),
(3, 52, 'Viewer'),
(3, 59, 'Developer'),
(3, 19, 'Developer'),
(3, 57, 'Developer'),
(3, 17, 'Viewer'),
(3, 42, 'Developer'),
(3, 62, 'Developer'),
(4, 3, 'Admin'),
(4, 70, 'Developer'),
(4, 31, 'Viewer'),
(4, 9, 'Developer'),
(4, 6, 'Viewer'),
(4, 46, 'Viewer'),
(4, 33, 'Viewer'),
(4, 62, 'Developer'),
(4, 8, 'Developer'),
(4, 58, 'Developer'),
(5, 3, 'Admin'),
(5, 38, 'Developer'),
(5, 51, 'Viewer'),
(5, 16, 'Developer'),
(5, 43, 'Viewer'),
(6, 3, 'Admin'),
(6, 15, 'Developer'),
(6, 12, 'Viewer'),
(6, 30, 'Developer'),
(6, 73, 'Developer'),
(6, 19, 'Developer'),
(6, 47, 'Developer'),
(6, 38, 'Developer'),
(6, 64, 'Developer'),
(6, 51, 'Developer'),
(7, 2, 'Admin'),
(7, 59, 'Developer'),
(7, 34, 'Developer'),
(7, 16, 'Viewer'),
(7, 6, 'Developer'),
(8, 1, 'Admin'),
(8, 7, 'Developer'),
(8, 17, 'Developer'),
(8, 64, 'Developer'),
(8, 27, 'Viewer'),
(9, 2, 'Admin'),
(9, 4, 'Viewer'),
(9, 26, 'Viewer'),
(9, 32, 'Developer'),
(9, 14, 'Developer'),
(9, 37, 'Developer'),
(10, 1, 'Admin'),
(10, 44, 'Developer'),
(10, 70, 'Viewer'),
(10, 2, 'Viewer'),
(10, 62, 'Developer'),
(11, 2, 'Admin'),
(11, 13, 'Developer'),
(11, 23, 'Developer'),
(11, 6, 'Developer'),
(11, 25, 'Developer'),
(11, 21, 'Developer'),
(12, 3, 'Admin'),
(12, 15, 'Viewer'),
(12, 50, 'Developer'),
(12, 38, 'Developer'),
(12, 24, 'Developer');

-- Zusätzliche Aufgaben
INSERT INTO tasks (project_id, title, description, status, priority, assigned_to, created_by) VALUES
(3, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 3.', 'In Progress', 'Medium', 42, 2),
(3, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 3.', 'To Do', 'Medium', 1, 1),
(3, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 3.', 'In Progress', 'Low', 52, 1),
(3, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 3.', 'To Do', 'Low', 52, 1),
(3, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 3.', 'In Progress', 'Medium', 27, 3),
(3, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 3.', 'Done', 'High', 42, 1),
(3, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 3.', 'Blocked', 'Medium', 59, 4),
(3, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 3.', 'Done', 'High', 1, 2),
(3, 'Unit Tests schreiben', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 3.', 'Blocked', 'Medium', 57, 4),
(3, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 3.', 'To Do', 'Low', 27, 2),
(3, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 3.', 'To Do', 'High', 52, 1),
(3, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 3.', 'To Do', 'High', 42, 4),
(3, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 3.', 'Blocked', 'Low', 52, 2),
(3, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 3.', 'To Do', 'Medium', 57, 3),
(3, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 3.', 'Done', 'Medium', 42, 4),
(3, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 3.', 'To Do', 'High', 1, 2),
(3, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 3.', 'In Progress', 'Low', 17, 2),
(3, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 3.', 'Done', 'High', 62, 4),
(3, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 3.', 'To Do', 'Medium', 1, 4),
(3, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 3.', 'To Do', 'Low', 17, 3),
(3, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 3.', 'Done', 'Medium', 59, 3),
(4, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 4.', 'In Progress', 'Low', 9, 2),
(4, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 4.', 'To Do', 'High', 70, 3),
(4, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 4.', 'In Progress', 'Medium', 46, 1),
(4, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 4.', 'Done', 'Medium', 58, 2),
(4, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 4.', 'Done', 'High', 8, 3),
(4, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 4.', 'Blocked', 'Low', 3, 1),
(4, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 4.', 'To Do', 'High', 62, 1),
(4, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 4.', 'To Do', 'High', 8, 2),
(4, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 4.', 'In Progress', 'High', 9, 4),
(4, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 4.', 'Done', 'Low', 62, 1),
(4, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 4.', 'In Progress', 'Low', 9, 4),
(4, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 4.', 'Blocked', 'High', 62, 3),
(4, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 4.', 'Done', 'High', 3, 3),
(4, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 4.', 'In Progress', 'High', 58, 2),
(4, 'Refactoring', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 4.', 'In Progress', 'Low', 46, 2),
(4, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 4.', 'In Progress', 'Medium', 70, 1),
(4, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 4.', 'Done', 'Low', 70, 4),
(4, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 4.', 'In Progress', 'Medium', 58, 4),
(4, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 4.', 'Done', 'Medium', 33, 2),
(4, 'Meeting Protokoll', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 4.', 'Blocked', 'Low', 3, 2),
(4, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 4.', 'To Do', 'Medium', 8, 4),
(5, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 5.', 'In Progress', 'High', 16, 4),
(5, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 5.', 'To Do', 'Medium', 51, 2),
(5, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 5.', 'Blocked', 'High', 16, 3),
(5, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 5.', 'Blocked', 'Medium', 43, 3),
(5, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 5.', 'Done', 'High', 3, 1),
(5, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 5.', 'To Do', 'High', 16, 4),
(5, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 5.', 'In Progress', 'Low', 3, 1),
(5, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 5.', 'In Progress', 'High', 16, 3),
(5, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 5.', 'To Do', 'Low', 16, 3),
(5, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 5.', 'Blocked', 'High', 38, 2),
(5, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 5.', 'In Progress', 'Low', 16, 3),
(5, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 5.', 'Done', 'High', 3, 2),
(5, 'Unit Tests schreiben', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 5.', 'To Do', 'Medium', 43, 4),
(5, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 5.', 'To Do', 'Low', 3, 2),
(5, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 5.', 'In Progress', 'Low', 38, 1),
(5, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 5.', 'To Do', 'Medium', 3, 2),
(5, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 5.', 'In Progress', 'High', 3, 2),
(5, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 5.', 'Blocked', 'High', 51, 1),
(5, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 5.', 'To Do', 'High', 51, 3),
(5, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 5.', 'Done', 'Low', 38, 3),
(5, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 5.', 'In Progress', 'Low', 38, 3),
(6, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 6.', 'To Do', 'High', 15, 1),
(6, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 6.', 'To Do', 'High', 15, 2),
(6, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 6.', 'Done', 'Low', 47, 2),
(6, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 6.', 'Done', 'High', 51, 4),
(6, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 6.', 'To Do', 'High', 19, 2),
(6, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 6.', 'In Progress', 'Low', 73, 2),
(6, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 6.', 'Done', 'Medium', 47, 1),
(6, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 6.', 'Blocked', 'High', 3, 4),
(6, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 6.', 'To Do', 'Medium', 30, 3),
(6, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 6.', 'Blocked', 'Low', 30, 1),
(6, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 6.', 'Blocked', 'Low', 38, 1),
(6, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 6.', 'In Progress', 'High', 73, 3),
(6, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 6.', 'In Progress', 'Medium', 47, 4),
(6, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 6.', 'In Progress', 'High', 73, 4),
(6, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 6.', 'In Progress', 'Low', 15, 1),
(6, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 6.', 'To Do', 'Low', 51, 2),
(6, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 6.', 'Done', 'Low', 30, 4),
(6, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 6.', 'Blocked', 'High', 15, 1),
(6, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 6.', 'To Do', 'Medium', 47, 1),
(6, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 6.', 'Blocked', 'Medium', 64, 2),
(6, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 6.', 'To Do', 'Low', 12, 4),
(7, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 7.', 'To Do', 'Medium', 34, 3),
(7, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 7.', 'Blocked', 'Low', 2, 2),
(7, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 7.', 'Blocked', 'Low', 59, 2),
(7, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 7.', 'To Do', 'Medium', 16, 2),
(7, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 7.', 'In Progress', 'High', 34, 3),
(7, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 7.', 'Blocked', 'High', 34, 2),
(7, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 7.', 'Done', 'Medium', 2, 4),
(7, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 7.', 'Blocked', 'High', 6, 4),
(7, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 7.', 'Done', 'Low', 59, 2),
(7, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 7.', 'Done', 'Medium', 2, 1),
(7, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 7.', 'To Do', 'Medium', 2, 3),
(7, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 7.', 'Done', 'High', 34, 4),
(7, 'Unit Tests schreiben', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 7.', 'Blocked', 'High', 6, 2),
(7, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 7.', 'Blocked', 'High', 34, 2),
(7, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 7.', 'Blocked', 'Medium', 2, 1),
(7, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 7.', 'To Do', 'Low', 6, 1),
(7, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 7.', 'Done', 'Low', 2, 3),
(7, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 7.', 'Done', 'Low', 6, 4),
(7, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 7.', 'Blocked', 'Medium', 59, 3),
(7, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 7.', 'Blocked', 'High', 16, 1),
(7, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 7.', 'In Progress', 'High', 2, 2),
(8, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 8.', 'In Progress', 'Medium', 7, 2),
(8, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 8.', 'In Progress', 'High', 64, 4),
(8, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 8.', 'In Progress', 'Low', 27, 4),
(8, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 8.', 'Done', 'Low', 1, 4),
(8, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 8.', 'Blocked', 'Low', 1, 1),
(8, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 8.', 'Done', 'Medium', 27, 1),
(8, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 8.', 'In Progress', 'High', 64, 2),
(8, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 8.', 'Done', 'Medium', 7, 1),
(8, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 8.', 'To Do', 'Low', 64, 4),
(8, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 8.', 'To Do', 'Medium', 17, 2),
(8, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 8.', 'Blocked', 'Medium', 1, 4),
(8, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 8.', 'Blocked', 'Low', 1, 1),
(8, 'Meeting Protokoll', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 8.', 'Blocked', 'High', 1, 1),
(8, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 8.', 'In Progress', 'Low', 7, 2),
(8, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 8.', 'Blocked', 'High', 7, 2),
(8, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 8.', 'Done', 'High', 7, 1),
(8, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 8.', 'To Do', 'High', 64, 1),
(8, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 8.', 'In Progress', 'Medium', 17, 3),
(8, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 8.', 'In Progress', 'Medium', 17, 3),
(8, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 8.', 'Done', 'High', 7, 3),
(8, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 8.', 'In Progress', 'Medium', 7, 1),
(9, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 9.', 'Blocked', 'Low', 37, 3),
(9, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 9.', 'Blocked', 'Medium', 26, 1),
(9, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 9.', 'To Do', 'High', 4, 2),
(9, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 9.', 'To Do', 'High', 4, 1),
(9, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 9.', 'To Do', 'Medium', 32, 1),
(9, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 9.', 'Blocked', 'Low', 32, 3),
(9, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 9.', 'Done', 'Medium', 14, 1),
(9, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 9.', 'Done', 'Medium', 26, 2),
(9, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 9.', 'Done', 'Low', 14, 4),
(9, 'Unit Tests schreiben', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 9.', 'In Progress', 'Medium', 26, 4),
(9, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 9.', 'In Progress', 'High', 32, 1),
(9, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 9.', 'Blocked', 'Low', 2, 2),
(9, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 9.', 'Done', 'Low', 26, 1),
(9, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 9.', 'To Do', 'Low', 26, 1),
(9, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 9.', 'In Progress', 'Medium', 26, 3),
(9, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 9.', 'To Do', 'Low', 37, 4),
(9, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 9.', 'Done', 'High', 2, 1),
(9, 'Refactoring', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 9.', 'Done', 'Low', 32, 3),
(9, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 9.', 'In Progress', 'High', 32, 4),
(9, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 9.', 'Blocked', 'Medium', 32, 2),
(9, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 9.', 'Blocked', 'Medium', 4, 2),
(10, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 10.', 'Done', 'High', 1, 1),
(10, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 10.', 'Done', 'High', 44, 4),
(10, 'Frontend Komponenten erstellen', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 10.', 'To Do', 'High', 70, 1),
(10, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 10.', 'To Do', 'Low', 44, 4),
(10, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 10.', 'To Do', 'Medium', 1, 3),
(10, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 10.', 'To Do', 'Low', 44, 1),
(10, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 10.', 'Blocked', 'High', 44, 1),
(10, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 10.', 'In Progress', 'Low', 2, 2),
(10, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 10.', 'Done', 'Low', 44, 4),
(10, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 10.', 'Blocked', 'Low', 1, 4),
(10, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 10.', 'Done', 'High', 2, 3),
(10, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 10.', 'In Progress', 'High', 2, 4),
(10, 'API Dokumentation', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 10.', 'Blocked', 'High', 1, 1),
(10, 'Meeting Protokoll', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 10.', 'Done', 'High', 62, 2),
(10, 'CI/CD Pipeline einrichten', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 10.', 'To Do', 'Low', 62, 2),
(10, 'Deployment vorbereiten', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 10.', 'To Do', 'Medium', 44, 3),
(10, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 10.', 'Done', 'Low', 70, 4),
(10, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 10.', 'To Do', 'High', 62, 2),
(10, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 10.', 'Done', 'Low', 62, 1),
(10, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 10.', 'To Do', 'Low', 70, 3),
(10, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 10.', 'Done', 'Low', 62, 3),
(11, 'Refactoring', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 11.', 'To Do', 'High', 13, 1),
(11, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 11.', 'In Progress', 'Low', 2, 1),
(11, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 11.', 'Blocked', 'High', 6, 3),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 11.', 'To Do', 'High', 2, 3),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 11.', 'To Do', 'High', 21, 3),
(11, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 11.', 'Done', 'High', 2, 2),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 11.', 'To Do', 'Medium', 23, 4),
(11, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 11.', 'To Do', 'Medium', 25, 3),
(11, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 11.', 'To Do', 'Medium', 6, 2),
(11, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 11.', 'Done', 'High', 2, 4),
(11, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 11.', 'Done', 'Medium', 21, 1),
(11, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 11.', 'Blocked', 'Low', 23, 3),
(11, 'Refactoring', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 11.', 'To Do', 'High', 13, 4),
(11, 'Anforderungsanalyse erstellen', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 11.', 'Done', 'Medium', 21, 1),
(11, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 11.', 'Done', 'Medium', 13, 3),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 11.', 'Done', 'High', 23, 3),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 11.', 'To Do', 'High', 13, 4),
(11, 'Code Review durchführen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 11.', 'Blocked', 'Medium', 6, 1),
(11, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 11.', 'Blocked', 'Low', 25, 3),
(11, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 11.', 'In Progress', 'Medium', 13, 4),
(11, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 11.', 'Done', 'Medium', 21, 4),
(12, 'Security Audit', 'Detailierte Beschreibung für Aufgabe 1 im Projekt 12.', 'Blocked', 'Medium', 24, 3),
(12, 'Bugfixing', 'Detailierte Beschreibung für Aufgabe 2 im Projekt 12.', 'In Progress', 'Low', 15, 2),
(12, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 3 im Projekt 12.', 'Done', 'Low', 50, 1),
(12, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 4 im Projekt 12.', 'Blocked', 'Medium', 15, 1),
(12, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 5 im Projekt 12.', 'To Do', 'Low', 3, 3),
(12, 'ER-Modell entwerfen', 'Detailierte Beschreibung für Aufgabe 6 im Projekt 12.', 'Done', 'High', 38, 2),
(12, 'Performance Tuning', 'Detailierte Beschreibung für Aufgabe 7 im Projekt 12.', 'In Progress', 'Low', 15, 1),
(12, 'Kundenfeedback einholen', 'Detailierte Beschreibung für Aufgabe 8 im Projekt 12.', 'Blocked', 'Low', 3, 1),
(12, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 9 im Projekt 12.', 'Blocked', 'Low', 24, 2),
(12, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 10 im Projekt 12.', 'Blocked', 'Medium', 15, 3),
(12, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 11 im Projekt 12.', 'Done', 'High', 50, 3),
(12, 'Präsentation vorbereiten', 'Detailierte Beschreibung für Aufgabe 12 im Projekt 12.', 'In Progress', 'High', 38, 2),
(12, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 13 im Projekt 12.', 'Done', 'Medium', 38, 3),
(12, 'User Stories definieren', 'Detailierte Beschreibung für Aufgabe 14 im Projekt 12.', 'Blocked', 'Low', 38, 1),
(12, 'Unit Tests schreiben', 'Detailierte Beschreibung für Aufgabe 15 im Projekt 12.', 'To Do', 'Medium', 3, 1),
(12, 'Refactoring', 'Detailierte Beschreibung für Aufgabe 16 im Projekt 12.', 'To Do', 'Medium', 15, 1),
(12, 'Sprint Planning', 'Detailierte Beschreibung für Aufgabe 17 im Projekt 12.', 'Blocked', 'High', 38, 4),
(12, 'Dokumentation verfassen', 'Detailierte Beschreibung für Aufgabe 18 im Projekt 12.', 'Done', 'Low', 38, 4),
(12, 'Datenmigration', 'Detailierte Beschreibung für Aufgabe 19 im Projekt 12.', 'In Progress', 'Medium', 24, 4),
(12, 'Lasttests durchführen', 'Detailierte Beschreibung für Aufgabe 20 im Projekt 12.', 'In Progress', 'High', 15, 1),
(12, 'Prototyp entwickeln', 'Detailierte Beschreibung für Aufgabe 21 im Projekt 12.', 'To Do', 'High', 50, 4);

